export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ID = "LOGIN_ID";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const CHANGE_DATA_SUPPLIER = "CHANGE_DATA_SUPPLIER";
export const CREATE_SUPPLIER_SUCCESS = "CREATE_SUPPLIER_SUCCESS";
export const CREATE_SUPPLIER_ERROR = "CREATE_SUPPLIER_ERROR";
export const CREATE_SUPPLIER_FAIL = "CREATE_SUPPLIER_FAIL";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const REFRESH_SUPPLIER = "REFRESH_SUPPLIER";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CHANGE_DATA_CATEGORY = "CHANGE_DATA_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const REFRESH_CATEGORY = "REFRESH_CATEGORY";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const CHANGE_DATA_PRODUCT = "CHANGE_DATA_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const REFRESH_PRODUCT = "REFRESH_PRODUCT";

export const GET_INVENTORIES = "GET_INVENTORIES";

export const GET_RECEIPTS = "GET_RECEIPTS";

export const GET_DISCOUNTS = "GET_DISCOUNTS";
export const CHANGE_DATA_DISCOUNT = "CHANGE_DATA_DISCOUNT";
export const CREATE_DISCOUNT_SUCCESS = "CREATE_DISCOUNT_SUCCESS";
export const CREATE_DISCOUNT_ERROR = "CREATE_DISCOUNT_ERROR";
export const CREATE_DISCOUNT_FAIL = "CREATE_DISCOUNT_FAIL";
export const DELETE_DISCOUNT = "DELETE_DISCOUNT";
export const REFRESH_DISCOUNT = "REFRESH_DISCOUNT";

export const GET_ROLES = "GET_ROLES";
export const CHANGE_DATA_ROLE = "CHANGE_DATA_ROLE";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_ERROR = "CREATE_ROLE_ERROR";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";
export const DELETE_ROLE = "DELETE_ROLE";
export const REFRESH_ROLE = "REFRESH_ROLE";

export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const CHANGE_DATA_USER = "CHANGE_DATA_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const DELETE_USER = "DELETE_USER";
export const REFRESH_USER = "REFRESH_USER";

export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const CHANGE_DATA_CUSTOMER = "CHANGE_DATA_CUSTOMER";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR";
export const CREATE_CUSTOMER_FAIL = "CREATE_CUSTOMER_FAIL";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const REFRESH_CUSTOMER = "REFRESH_CUSTOMER";

export const GET_INVOICES = "GET_INVOICES";
export const GET_INVOICES_DETAIL = "GET_INVOICES_DETAIL";
export const CHANGE_DATA_INVOICE = "CHANGE_DATA_INVOICE";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_ERROR = "CREATE_INVOICE_ERROR";
export const CREATE_INVOICE_FAIL = "CREATE_INVOICE_FAIL";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const REFRESH_INVOICE = "REFRESH_INVOICE";

export const CHANGE_DATA_CART = "CHANGE_DATA_CART";
export const CHANGE_DATA = "CHANGE_DATA";
export const CREATE_INVOICE = "CREATE_INVOICE";
