export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const CHANGE_DATA_SUPPLIER = "CHANGE_DATA_SUPPLIER";
export const CREATE_SUPPLIER_SUCCESS = "CREATE_SUPPLIER_SUCCESS";
export const CREATE_SUPPLIER_ERROR = "CREATE_SUPPLIER_ERROR";
export const CREATE_SUPPLIER_FAIL = "CREATE_SUPPLIER_FAIL";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const REFRESH_SUPPLIER = "REFRESH_SUPPLIER";

export const GET_CATEGORIES = "GET_CATEGORIES";
